### ISSUE TITLE
http://scala-ide.org/ is down

### ISSUE THREAD

**Issue by do4k** [scala-ide/scala-ide.github.com#116]
![image](https://user-images.githubusercontent.com/464887/149511978-889aa26c-d9be-4899-84b3-9c809fb1725c.png)

**Comment by mkurz** [comment]
Scala IDE is dead. Alternatives are [JetBrains IntelliJ IDEA](https://www.jetbrains.com/de-de/idea/) or [Metals](https://scalameta.org/metals/)
