### ISSUE TITLE
Update "team" page

### ISSUE THREAD

**Issue by Kwestor** [scala-ide/scala-ide.github.com#90]
I would like update some information on this page and in docs.

As a starter I took a look at "Team" page: http://scala-ide.org/team.html - this info is obviously out of date.

I plan to split team into `Current Team` and `Previous contributors`. In current team I would include active developers: Iulian, Simon, Wiesław (I'll add him), Luc, Mirco and Mirko. Rest will be moved into separate paragraph.

@dragos Is that ok for you?

**Comment by mkurz** [comment]
The roadmap page is also out of date.

**Comment by sschaef** [comment]
I'm going to have a look at this later in the week.

**Comment by sschaef** [comment]
Fixed by https://github.com/scala-ide/scala-ide.github.com/commit/366d4153de49103002197b3f9ed5be36b3ac3799
